[package]
name = "cs"
version = "2.0.2"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
camino = "1.1.9"
clap = { version = "4.5", features = ["derive"] }
unidecode = "0.3.0"

[dev-dependencies]
assert_cmd = "2.0.16"
camino-tempfile-ext = "0.3.3"
predicates = "3.1.3"
