[package]
name = "alsort"
version = "1.1.4"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
camino = "1.1.9"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
camino-tempfile-ext = "0.3.3"
