[package]
name = "alsort"
version = "1.1.3"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
camino = "1.1.9"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
assert_fs = "1.1.2"
